//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeITProfile
    {
        public string Id { get; set; }
        public string Full_Name { get; set; }
        public int CompanyId { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string Company_Name { get; set; }
        public string Employee_Id { get; set; }
        public string Official_Email { get; set; }
        public string Official_Email_Password { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyEmployeeStrength { get; set; }
        public string CompanyFoundedMonthYear { get; set; }
        public string CompanyFounder { get; set; }
        public string CompanyOfficialContact { get; set; }
        public string CompanyOfficialEmail { get; set; }
        public string CompanyWebsite { get; set; }
        public string HRId { get; set; }
        public string HRName { get; set; }
        public string HRMobile { get; set; }
        public string HROfficialEmail { get; set; }
        public string LeadId { get; set; }
        public string LeadName { get; set; }
        public string LeadMobile { get; set; }
        public string LeadOfficialEmail { get; set; }
        public string ManagerId { get; set; }
        public string ManagerName { get; set; }
        public string ManagerMobile { get; set; }
        public string ManagerOfficialEmail { get; set; }
        public string Mobile { get; set; }
        public string Email_Id { get; set; }
        public string Batch { get; set; }
        public string Team { get; set; }
        public string Permanent_Address { get; set; }
        public string Current_Address { get; set; }
        public string PAN { get; set; }
        public string Adhaar { get; set; }
        public string UAN { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<decimal> Joining_Salary { get; set; }
        public string Joining_Designation { get; set; }
        public Nullable<decimal> Current_Salary { get; set; }
        public string Current_Designation { get; set; }
        public Nullable<System.DateTime> Resignation_Date { get; set; }
        public Nullable<System.DateTime> Last_Working_Day { get; set; }
        public string ProjectName { get; set; }
        public string ProjectTechnologies { get; set; }
        public string ProjectDescription { get; set; }
    }
}
